### ISSUE TITLE
getting TypeError: matchMonthDay.exec is not a function or its return value is not iterable

### ISSUE THREAD

**Issue by rogereiddir** [haraka/haraka-plugin-log-reader#24]
Hello ,
 i am getting this error when hitting the route /logs/:uuid

can someone help thanks

> [CRIT] [-] [core] TypeError: matchMonthDay.exec is not a function or its return value is not iterable
> [CRIT] [-] [core]     at matched.split.forEach (/etc/haraka/node_modules/haraka-plugin-log-reader/index.js:119:36)
> [CRIT] [-] [core]     at Array.forEach (<anonymous>)
> [CRIT] [-] [core]     at Object.exports.asHtml (/etc/haraka/node_modules/haraka-plugin-log-reader/index.js:110:23)
> [CRIT] [-] [core]     at /etc/haraka/node_modules/haraka-plugin-log-reader/index.js:76:13
> [CRIT] [-] [core]     at Socket.<anonymous> (/etc/haraka/node_modules/haraka-plugin-log-reader/index.js:99:5)
> [CRIT] [-] [core]     at Socket.emit (events.js:194:15)
> [CRIT] [-] [core]     at endReadableNT (_stream_readable.js:1125:12)
> [CRIT] [-] [core]     at process._tickCallback (internal/process/next_tick.js:63:19)
> [NOTICE] [-] [core] Shutting down
>

**Comment by lacmuch** [comment]
i've put [, monthDay] = matchMonthDay.exec(line); in try...catch and it works, but not showing the month day

**Comment by msimerson** [comment]
I've since applied @lacmuch 's suggestion and with no follow up of logs to investigate why, I see nothing left to do here.
